# Checks if the Description includes # SW-HW Integration Testing Pull Request Review Checklist' AND
# checks all Regex are satisfied
.pr-checklist-validator-description: &pr-checklist-validator-description
  do: description
  and:
    # Checking if the description is empty
    - must_include:
        regex: '# SW-HW Integration Testing Pull Request Review Checklist'
        message: '# SW-HW Integration Testing Pull Request Review Checklist'
    # Checking when both OK and NOK / NA checks are selected
    - must_exclude:
        regex: '# SW-HW Integration Testing Pull Request Review Checklist(?:(?!<!-- END_INTEGRATION_CHECKLIST -->)[\s\S])*?-\s*\[x\]\s*OK\s*:\s*-\s*\[x\]\s*NOK\s*\/\s*NA\s*:\s*[^\r\n]*'
        regex_flag: m
        message: 'Selecting both "OK" and "NOK/NA" checks is invalid. Use only one of the checks.'
    # NOK/NA selected but default text not updated
    - must_exclude:
        regex: '# SW-HW Integration Testing Pull Request Review Checklist(?:(?!<!-- END_INTEGRATION_CHECKLIST -->)[\s\S])*?-\s*\[\s\]\s*OK\s*:\s*-\s*\[x\]\s*NOK\s*\/\s*NA\s*:\s*\[enter text here\]'
        regex_flag: m
        message: 'When NOK/NA is selected, replace the placeholder text with a proper reason.'
    # Neither OK nor NOK/NA selected
    - must_exclude:
        regex: '# SW-HW Integration Testing Pull Request Review Checklist(?:(?!<!-- END_INTEGRATION_CHECKLIST -->)[\s\S])*?-\s*\[\s\]\s*OK\s*:\s*-\s*\[\s\]\s*NOK\s*\/\s*NA\s*:\s*[^\r\n]*'
        regex_flag: m
        message: 'Either OK or NOK/NA must be selected.'
    # NOK/NA selected but no comment provided
    - must_exclude:
        regex: '# SW-HW Integration Testing Pull Request Review Checklist(?:(?!<!-- END_INTEGRATION_CHECKLIST -->)[\s\S])*?-\s*\[\s\]\s*OK\s*:\s*-\s*\[x\]\s*NOK\s*\/\s*NA\s*:\s*$'
        regex_flag: m
        message: 'When NOK/NA is selected, please provide a reason.'
    # Valid OK selection without default text
    - must_exclude:
        regex: '# SW-HW Integration Testing Pull Request Review Checklist(?:(?!<!-- END_INTEGRATION_CHECKLIST -->)[\s\S])*?-\s*\[x\]\s*OK\s*:\s*\r?\n\s*-\s*\[\s*\]\s*NOK\s*\/\s*NA\s*:\s*(?!\s*\[enter text here\]\s*$)(?!\s*$)[^\r\n]+'
        regex_flag: m
        message: 'When OK is selected, no changes should be made to the default text.'

.pr-dev-checklist-validator-description: &pr-dev-checklist-validator-description
  do: description
  and:
    # Checklist header must be present
    - must_include:
        regex: '# Test case \(UT, SCTF, ITF dev\) Pull Request Review Checklist'
        message: '# Test case (UT, SCTF, ITF dev) Pull Request Review Checklist is missing from PR description'
    # When OK is selected, changes or editing is not allowed
    - must_exclude:
        regex: '# Test case \(UT, SCTF, ITF dev\) Pull Request Review Checklist(?:(?!<!-- END_DEVELOPER_CHECKLIST -->)[\s\S])*?-\s*\[x\]\s*OK\s*:\s*\r?\n\s*-\s*\[\s*\]\s*NOK\s*\/\s*NA\s*:\s*(?!\s*\[enter text here\]\s*$)(?!\s*$)[^\r\n]+'
        regex_flag: m
        message: 'When OK is selected, no changes should be made to the default text.'
    # Checking when both OK and NOK / NA checks are selected
    - must_exclude:
        regex: '# Test case \(UT, SCTF, ITF dev\) Pull Request Review Checklist(?:(?!<!-- END_DEVELOPER_CHECKLIST -->)[\s\S])*?-\s*\[x\]\s*OK\s*:\s*-\s*\[x\]\s*NOK\s*\/\s*NA\s*:\s*[^\r\n]*'
        regex_flag: m
        message: 'Selecting both "OK" and "NOK/NA" checks is invalid. Use only one of the checks.'
    # Checking when NOK \ NA is selected
    - must_exclude:
        regex: '# Test case \(UT, SCTF, ITF dev\) Pull Request Review Checklist(?:(?!<!-- END_DEVELOPER_CHECKLIST -->)[\s\S])*?-\s*\[\s\]\s*OK\s*:\s*-\s*\[x\]\s*NOK\s*\/\s*NA\s*:\s*\[enter text here\]'
        regex_flag: m
        message: 'When NOK/NA is selected, replace the placeholder text with a proper reason.'
    # NOK/NA selected but no comment provided
    - must_exclude:
        regex: '# Test case \(UT, SCTF, ITF dev\) Pull Request Review Checklist(?:(?!<!-- END_DEVELOPER_CHECKLIST -->)[\s\S])*?-\s*\[\s\]\s*OK\s*:\s*-\s*\[x\]\s*NOK\s*\/\s*NA\s*:\s*$'
        regex_flag: m
        message: 'When NOK/NA is selected, please provide a reason.'
    # At least one test type must be selected
    - must_exclude:
        regex: '# Test case \(UT, SCTF, ITF dev\) Pull Request Review Checklist(?:(?!<!-- END_DEVELOPER_CHECKLIST -->)[\s\S])*?-\s\[\s\]\sRequirements-based test\b[\s\S]*?^\s*-\s\[\s\]\sInterface test\b[\s\S]*?^\s*-\s\[\s\]\sFault injection test\b[\s\S]*?^\s*-\s\[\s\]\sResource usage evaluation test\b[\s\S]*?^\s*-\s\[\s\]\sVerification of the control flow and data flow\b[\s\S]*?^\s*-\s\[\s\]\s'
        regex_flag: m
        message: Select at least one test type.
    # Only one test type may be selected.
    - must_exclude:
        regex: '# Test case \(UT, SCTF, ITF dev\) Pull Request Review Checklist(?:(?!<!-- END_DEVELOPER_CHECKLIST -->)[\s\S])*?-\s*\[x\]\s*(?:Requirements-based test|Interface test|Fault injection test|Resource usage evaluation test|Verification of the control flow and data flow)[\s\S]*?-\s*\[x\]\s*(?:Requirements-based test|Interface test|Fault injection test|Resource usage evaluation test|Verification of the control flow and data flow)'
        regex_flag: m
        message: Only one test type may be selected.
    # Requirements-based test selected but one of its sub-checks is empty
    - must_exclude:
        regex: '# Test case \(UT, SCTF, ITF dev\) Pull Request Review Checklist(?:(?!<!-- END_DEVELOPER_CHECKLIST -->)[\s\S])*?-\s\[x\]\sRequirements-based test\b[\s\S]*?^\s*-\s\[\s\]\sOK:\s*\s*-\s\[\s\]\sNOK\s*\/\s*NA\s*:\s*\[enter text here\][\s\S]*?^\s*-\s\[\s\]\sInterface test\b'
        regex_flag: m
        message: Requirements-based test is selected, so all its sub-checks must be filled
    # Interface test selected but one of its sub-checks is empty
    - must_exclude:
        regex: '# Test case \(UT, SCTF, ITF dev\) Pull Request Review Checklist(?:(?!<!-- END_DEVELOPER_CHECKLIST -->)[\s\S])*?-\s\[x\]\sInterface test\b[\s\S]*?^\s*-\s\[\s\]\sOK:\s*\s*-\s\[\s\]\sNOK\s*\/\s*NA\s*:\s*\[enter text here\][\s\S]*?^\s*-\s\[\s\]\sFault injection test\b'
        regex_flag: m
        message: Interface test is selected, so all its sub-checks must be filled
    # Fault injection test selected but its sub-check is empty
    - must_exclude:
        regex: '# Test case \(UT, SCTF, ITF dev\) Pull Request Review Checklist(?:(?!<!-- END_DEVELOPER_CHECKLIST -->)[\s\S])*?-\s\[x\]\sFault injection test\b[\s\S]*?^\s*-\s\[\s\]\sOK:\s*\s*-\s\[\s\]\sNOK\s*\/\s*NA\s*:\s*\[enter text here\][\s\S]*?^\s*-\s\[\s\]\sResource usage evaluation test\b'
        regex_flag: m
        message: Fault injection test is selected, so its sub-check must be filled
    # Resource usage evaluation test selected but its sub-check is empty
    - must_exclude:
        regex: '# Test case \(UT, SCTF, ITF dev\) Pull Request Review Checklist(?:(?!<!-- END_DEVELOPER_CHECKLIST -->)[\s\S])*?-\s\[x\]\sResource usage evaluation test\b[\s\S]*?^\s*-\s\[\s\]\sOK:\s*\s*-\s\[\s\]\sNOK\s*\/\s*NA\s*:\s*\[enter text here\][\s\S]*?^\s*-\s\[\s\]\sVerification of the control flow and data flow\b'
        regex_flag: m
        message: Resource usage evaluation test is selected, so its sub-check must be filled
    # Verification of control/data flow selected but its sub-check is empty
    - must_exclude:
        regex: '# Test case \(UT, SCTF, ITF dev\) Pull Request Review Checklist(?:(?!<!-- END_DEVELOPER_CHECKLIST -->)[\s\S])*?-\s\[x\]\sVerification of the control flow and data flow\b[\s\S]*?^\s*-\s\[\s\]\sOK:\s*\s*-\s\[\s\]\sNOK\s*\/\s*NA\s*:\s*\[enter text here\][\s\S]*?^\s*'
        regex_flag: m
        message: Verification of the control flow and data flow is selected, so its sub-check must be filled

# Bot checks when the description is empty or the testing checklist added with heading
# SW-HW Integration Testing Pull Request Review Checklist'
version: 2
mergeable:
  - when: pull_request.*
    name: Integration Checklist Validation
    validate:
      - do: or
        validate:
          - do: description
            must_exclude:
              regex: '# SW-HW Integration Testing Pull Request Review Checklist'
              regex_flag: m
          - *pr-checklist-validator-description
    fail:
      - do: checks
        status: failure
        payload:
          title: 'SW-HW Integration Testing Pull Request Review Checklist FAILED ❌'
          summary: |
            How to Fix:
              - Select exactly ONE option - either "OK" OR "NOK / NA".
              - If "NOK / NA" is selected replace "[enter text here]" with a valid reason why is it selected.
              - Do not modify default place holder text "[enter text here]" if "NOK / NA" is not selected.
          text: "{{#each validationSuites}}\n
                #### {{{statusIcon status}}} Validator: {{toUpperCase name}}\n
                {{#each validations }} * {{{statusIcon status}}} ***{{{ description }}}***\n
                       Input : {{{details.input}}}\n
                       Settings : {{{displaySettings details.settings}}}\n
                       {{/each}}\n
                {{/each}}"
  - when: pull_request.*
    name: Developer Checklist Validation
    validate:
      - do: or
        validate:
          - do: description
            must_exclude:
              regex: '# Test case \(UT, SCTF, ITF dev\) Pull Request Review Checklist'
              regex_flag: m
          - *pr-dev-checklist-validator-description
    fail:
      - do: checks
        status: failure
        payload:
          title: 'Test case (UT, SCTF, ITF dev) Pull Request Review Checklist FAILED ❌'
          summary: |
            How to Fix:
              - Select exactly ONE option - either "OK" OR "NOK / NA".
              - If "NOK / NA" is selected replace "[enter text here]" with a valid reason why is it selected.
              - Do not modify default place holder text "[enter text here]" if "NOK / NA" is not selected.
              - For checklist 4 select one type of test from below list:
                - Requirements-based test
                - Interface test
                - Fault injection test
                - Resource usage evaluation test
                - Verification of the control flow and data flow
              - If your test does not fall under any of above list select option "Other" and fill in a valid reason.
          text: "{{#each validationSuites}}\n
                #### {{{statusIcon status}}} Validator: {{toUpperCase name}}\n
                {{#each validations }} * {{{statusIcon status}}} ***{{{ description }}}***\n
                       Input : {{{details.input}}}\n
                       Settings : {{{displaySettings details.settings}}}\n
                       {{/each}}\n
                {{/each}}"
